/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/market/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical OHLCV bars
         * @description Returns bars in ascending time order. Interval/range combinations the data source cannot serve are rejected with a `VALIDATION` problem.
         */
        get: operations["getBars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The process is alive */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready to serve market data */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias of /readiness */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed health including the market-data connection state */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: components["schemas"]["problem.schema"];
        BarsResponse: components["schemas"]["bars-response.schema"];
        HealthDetail: components["schemas"]["health-detail.schema"];
        /** @description Ticker symbol (upper case). */
        Symbol: string;
        /** @enum {string} */
        Interval: "1m" | "5m" | "15m" | "1h" | "1d";
        /** @enum {string} */
        Range: "1d" | "5d" | "1mo" | "3mo" | "1y";
        /** Format: uuid */
        Uuid: string;
        /**
         * Format: date-time
         * @description RFC 3339 date-time in UTC with a trailing 'Z'.
         */
        UtcTimestamp: string;
        /** @description Non-negative decimal string, up to 13 integer and 6 fractional digits. */
        Price: string;
        /** @description Non-negative integer within the exactly representable range of IEEE-754 doubles. */
        SafeCount: number;
        Bar: {
            /** @description Bar open time (UTC). */
            time: components["schemas"]["UtcTimestamp"];
            open: components["schemas"]["Price"];
            high: components["schemas"]["Price"];
            low: components["schemas"]["Price"];
            close: components["schemas"]["Price"];
            volume: components["schemas"]["SafeCount"];
        };
        /**
         * BarsResponse
         * @description Historical OHLCV bars in ascending time order. Unsupported interval/range combinations are rejected with a VALIDATION problem.
         */
        "bars-response.schema": {
            symbol: components["schemas"]["Symbol"];
            interval: components["schemas"]["Interval"];
            range: components["schemas"]["Range"];
            /** @enum {string} */
            source: "IBKR" | "MOCK";
            cached: boolean;
            bars: components["schemas"]["Bar"][];
            $defs: {
                /** @enum {string} */
                Interval: "1m" | "5m" | "15m" | "1h" | "1d";
                /** @enum {string} */
                Range: "1d" | "5d" | "1mo" | "3mo" | "1y";
                Bar: {
                    /** @description Bar open time (UTC). */
                    time: components["schemas"]["UtcTimestamp"];
                    open: components["schemas"]["Price"];
                    high: components["schemas"]["Price"];
                    low: components["schemas"]["Price"];
                    close: components["schemas"]["Price"];
                    volume: components["schemas"]["SafeCount"];
                };
            };
        };
        /** @enum {string} */
        ErrorCategory: "VALIDATION" | "INSTRUMENT_NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "STALE_MARKET_DATA" | "BROKER_REJECTED" | "BROKER_UNAVAILABLE" | "SERVICE_UNAVAILABLE" | "INTERNAL";
        /**
         * Problem
         * @description Error response body (compatible with RFC 9457 problem details) with a stable machine-readable category. Never contains stack traces or internal details.
         */
        "problem.schema": {
            type: string;
            title: string;
            status: number;
            category: components["schemas"]["ErrorCategory"];
            detail?: string;
            correlationId: components["schemas"]["Uuid"];
            errors?: {
                field: string;
                message: string;
            }[];
            $defs: {
                /** @enum {string} */
                ErrorCategory: "VALIDATION" | "INSTRUMENT_NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "STALE_MARKET_DATA" | "BROKER_REJECTED" | "BROKER_UNAVAILABLE" | "SERVICE_UNAVAILABLE" | "INTERNAL";
            };
        };
        /**
         * HealthDetail
         * @description Detailed health of the realtime gateway, including its market-data connection state.
         */
        "health-detail.schema": {
            /** @enum {string} */
            status: "UP" | "DEGRADED" | "DOWN";
            /**
             * @description Active market-data source for the lifetime of the process.
             * @enum {string}
             */
            source: "IBKR" | "MOCK";
            /** @enum {string} */
            connectionState: "DISCONNECTED" | "CONNECTING" | "AUTHENTICATING" | "READY" | "DEGRADED" | "RECONNECTING";
            since: components["schemas"]["UtcTimestamp"];
            activeSymbols: components["schemas"]["SafeCount"];
            wsClients: components["schemas"]["SafeCount"];
            lastErrorCategory: string | null;
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem.schema"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBars: {
        parameters: {
            query: {
                symbol: components["schemas"]["Symbol"];
                interval: components["schemas"]["Interval"];
                range: components["schemas"]["Range"];
            };
            header?: {
                "X-Correlation-Id"?: components["schemas"]["Uuid"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bars */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["bars-response.schema"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["health-detail.schema"];
                };
            };
        };
    };
}
