/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio summary and account metrics */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current positions */
        get: operations["listPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders, newest first */
        get: operations["listOrders"];
        put?: never;
        /**
         * Place an order (idempotent)
         * @description Validates the request, records the order intent, and submits it to the broker once.
         *     - `201`: the broker accepted or definitively rejected the order.
         *     - `202`: the order is waiting for confirmation (`PENDING_CONFIRMATION`), or the broker outcome is being verified (`UNKNOWN`).
         */
        post: operations["placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Request cancellation of an open order
         * @description The order moves to `CANCEL_PENDING` until the broker confirms the cancellation. Fills that arrive before that are still applied.
         */
        delete: operations["cancelOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm or decline a pending broker confirmation message
         * @description Only valid while the order is `PENDING_CONFIRMATION`. The broker may respond with another confirmation message, and chains are bounded.
         */
        post: operations["confirmOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List executions, newest first */
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the watchlist */
        get: operations["getWatchlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a symbol to the watchlist */
        post: operations["addWatchlistItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a symbol from the watchlist */
        delete: operations["removeWatchlistItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search instruments by symbol or name */
        get: operations["searchInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent news for a symbol, newest first */
        get: operations["listNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: components["schemas"]["problem.schema"];
        /**
         * @description Order lifecycle status. Terminal: FILLED, CANCELLED, REJECTED, FAILED. UNKNOWN means the broker outcome is uncertain and is resolved by reconciliation, never by automatic resubmission.
         * @enum {string}
         */
        OrderStatus: "CREATED" | "SUBMISSION_PENDING" | "PENDING_CONFIRMATION" | "SUBMITTED" | "PARTIALLY_FILLED" | "FILLED" | "CANCEL_PENDING" | "CANCELLED" | "REJECTED" | "FAILED" | "UNKNOWN";
        PlaceOrderRequest: components["schemas"]["place-order-request.schema"];
        OrderConfirmationRequest: components["schemas"]["order-confirmation-request.schema"];
        Order: components["schemas"]["order.schema"];
        Execution: components["schemas"]["execution.schema"];
        Position: components["schemas"]["position.schema"];
        PortfolioSummary: components["schemas"]["portfolio-summary.schema"];
        Instrument: components["schemas"]["instrument.schema"];
        Watchlist: components["schemas"]["watchlist.schema"];
        AddWatchlistItemRequest: components["schemas"]["add-watchlist-item-request.schema"];
        NewsArticle: components["schemas"]["news-article.schema"];
        /** Format: uuid */
        Uuid: string;
        /** @description Signed monetary decimal string (e.g. P&L). */
        SignedMoney: string;
        /** @description ISO 4217 currency code. */
        CurrencyCode: string;
        /**
         * OptionalMetric
         * @description A metric that may be unavailable from the broker. Unavailable metrics are never estimated: available=false and value=null.
         */
        "optional-metric.schema": {
            available: boolean;
            value: components["schemas"]["SignedMoney"] | null;
            currency: components["schemas"]["CurrencyCode"] | null;
        } & (unknown & unknown);
        /**
         * Format: date-time
         * @description RFC 3339 date-time in UTC with a trailing 'Z'.
         */
        UtcTimestamp: string;
        /**
         * PortfolioSummary
         * @description Account-level metrics. Metrics not provided by the broker are reported as unavailable.
         */
        "portfolio-summary.schema": {
            /** @enum {string} */
            accountMode: "MOCK" | "IBKR_PAPER";
            netLiquidation: components["schemas"]["optional-metric.schema"];
            cash: components["schemas"]["optional-metric.schema"];
            buyingPower: components["schemas"]["optional-metric.schema"];
            excessLiquidity: components["schemas"]["optional-metric.schema"];
            dayPnl: components["schemas"]["optional-metric.schema"];
            unrealizedPnl: components["schemas"]["optional-metric.schema"];
            realizedPnl: components["schemas"]["optional-metric.schema"];
            asOf: components["schemas"]["UtcTimestamp"];
        };
        /** @enum {string} */
        ErrorCategory: "VALIDATION" | "INSTRUMENT_NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "STALE_MARKET_DATA" | "BROKER_REJECTED" | "BROKER_UNAVAILABLE" | "SERVICE_UNAVAILABLE" | "INTERNAL";
        /**
         * Problem
         * @description Error response body (compatible with RFC 9457 problem details) with a stable machine-readable category. Never contains stack traces or internal details.
         */
        "problem.schema": {
            type: string;
            title: string;
            status: number;
            category: components["schemas"]["ErrorCategory"];
            detail?: string;
            correlationId: components["schemas"]["Uuid"];
            errors?: {
                field: string;
                message: string;
            }[];
            $defs: {
                /** @enum {string} */
                ErrorCategory: "VALIDATION" | "INSTRUMENT_NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "STALE_MARKET_DATA" | "BROKER_REJECTED" | "BROKER_UNAVAILABLE" | "SERVICE_UNAVAILABLE" | "INTERNAL";
            };
        };
        /** @description Ticker symbol (upper case). */
        Symbol: string;
        /** @description Signed decimal string (negative for short positions). */
        SignedQuantity: string;
        /** @description Non-negative decimal string, up to 13 integer and 6 fractional digits. */
        Price: string;
        /**
         * Position
         * @description Current position in an instrument. Negative quantity means short.
         */
        "position.schema": {
            symbol: components["schemas"]["Symbol"];
            quantity: components["schemas"]["SignedQuantity"];
            averageCost: components["schemas"]["Price"];
            marketValue: components["schemas"]["optional-metric.schema"];
            unrealizedPnl: components["schemas"]["optional-metric.schema"];
            realizedPnl: components["schemas"]["optional-metric.schema"];
        };
        /** @description Opaque identifier (e.g. broker order id, client order id). */
        Identifier: string;
        /**
         * @description What the user intends. SHORT opens or increases a short position.
         * @enum {string}
         */
        OrderIntent: "BUY" | "SELL" | "SHORT";
        /**
         * @description Side sent to the broker (a SHORT intent is submitted as SELL).
         * @enum {string}
         */
        BrokerSide: "BUY" | "SELL";
        /** @enum {string} */
        OrderType: "MARKET" | "LIMIT";
        /** @description Non-negative decimal string, up to 15 integer and 4 fractional digits. */
        Quantity: string;
        /** @enum {string} */
        TimeInForce: "DAY" | "GTC";
        /**
         * Order
         * @description Order resource. A PENDING_CONFIRMATION order carries the broker's confirmation message.
         */
        "order.schema": {
            id: components["schemas"]["Uuid"];
            clientOrderId: components["schemas"]["Identifier"];
            brokerOrderId: components["schemas"]["Identifier"] | null;
            symbol: components["schemas"]["Symbol"];
            intent: components["schemas"]["OrderIntent"];
            brokerSide: components["schemas"]["BrokerSide"];
            orderType: components["schemas"]["OrderType"];
            quantity: components["schemas"]["Quantity"];
            filledQuantity: components["schemas"]["Quantity"];
            limitPrice: components["schemas"]["Price"] | null;
            averageFillPrice: components["schemas"]["Price"] | null;
            timeInForce: components["schemas"]["TimeInForce"];
            status: components["schemas"]["OrderStatus"];
            pendingConfirmation: {
                message: string;
            } | null;
            rejectionReason: string | null;
            createdAt: components["schemas"]["UtcTimestamp"];
            submittedAt: components["schemas"]["UtcTimestamp"] | null;
            updatedAt: components["schemas"]["UtcTimestamp"];
        } & unknown;
        /**
         * PlaceOrderRequest
         * @description Order placement request. LIMIT orders require limitPrice; MARKET orders must not include it. Backend validation is authoritative (e.g. quantity > 0, tick size, configured limits).
         */
        "place-order-request.schema": {
            symbol: components["schemas"]["Symbol"];
            intent: components["schemas"]["OrderIntent"];
            orderType: components["schemas"]["OrderType"];
            quantity: components["schemas"]["Quantity"];
            limitPrice?: components["schemas"]["Price"];
            timeInForce: components["schemas"]["TimeInForce"];
        } & (unknown & unknown);
        /**
         * OrderConfirmationRequest
         * @description Confirms or declines a pending broker confirmation message for an order in PENDING_CONFIRMATION.
         */
        "order-confirmation-request.schema": {
            confirm: boolean;
        };
        /** @description Non-negative monetary decimal string, up to 15 integer and 4 fractional digits. */
        Money: string;
        /**
         * Execution
         * @description A fill of an order.
         */
        "execution.schema": {
            id: components["schemas"]["Uuid"];
            orderId: components["schemas"]["Uuid"];
            symbol: components["schemas"]["Symbol"];
            side: components["schemas"]["BrokerSide"];
            quantity: components["schemas"]["Quantity"];
            price: components["schemas"]["Price"];
            commission: components["schemas"]["Money"] | null;
            currency: components["schemas"]["CurrencyCode"];
            executedAt: components["schemas"]["UtcTimestamp"];
        };
        /** @description Non-negative integer within the exactly representable range of IEEE-754 doubles. */
        SafeCount: number;
        /**
         * Watchlist
         * @description The persisted watchlist, ordered by position.
         */
        "watchlist.schema": {
            id: components["schemas"]["Uuid"];
            items: {
                symbol: components["schemas"]["Symbol"];
                position: components["schemas"]["SafeCount"];
            }[];
        };
        /**
         * AddWatchlistItemRequest
         * @description Adds a symbol to the watchlist.
         */
        "add-watchlist-item-request.schema": {
            symbol: components["schemas"]["Symbol"];
        };
        /** @description Signed decimal rate in percent (e.g. an annualized borrow fee). */
        Rate: string;
        /**
         * Shortability
         * @description Shortability as reported by the broker; never invented. NOT_SHORTABLE: short orders are rejected before submission. UNAVAILABLE (no data, lookup failure, or stale data): short orders are allowed and the broker remains the final authority. Details are present only when the broker provides them.
         */
        "shortability.schema": {
            /** @enum {string} */
            status: "SHORTABLE" | "NOT_SHORTABLE" | "UNAVAILABLE";
            availableQuantity: components["schemas"]["SafeCount"] | null;
            borrowFeeRate: components["schemas"]["Rate"] | null;
            asOf: components["schemas"]["UtcTimestamp"] | null;
        } & unknown;
        /**
         * Instrument
         * @description Resolved instrument metadata.
         */
        "instrument.schema": {
            symbol: components["schemas"]["Symbol"];
            name: string | null;
            exchange: string;
            currency: components["schemas"]["CurrencyCode"];
            /** @enum {string} */
            assetType: "STK";
            shortability: components["schemas"]["shortability.schema"];
        };
        /**
         * NewsInsight
         * @description Structured AI analysis of a single article. Evidence references the analysed article. Scores are informational only and never drive trading actions.
         */
        "news-insight.schema": {
            summary: string;
            /** @enum {string} */
            sentiment: "POSITIVE" | "NEGATIVE" | "NEUTRAL" | "MIXED";
            sentimentScore: number;
            relevanceScore: number;
            catalysts: {
                /** @enum {string} */
                type: "EARNINGS" | "GUIDANCE" | "M_AND_A" | "ANALYST_RATING" | "REGULATORY" | "PRODUCT" | "MANAGEMENT" | "MACRO" | "OTHER";
                description: string;
            }[];
            confidence: number;
            evidence: components["schemas"]["Uuid"][];
            flags: ("LOW_CONFIDENCE" | "UNSUPPORTED_NUMBER" | "SYMBOL_MISMATCH")[];
        };
        /**
         * Enrichment
         * @description AI enrichment of an article, with the prompt and model versions that produced it.
         */
        "enrichment.schema": {
            promptVersion: string;
            model: string;
            modelVersion: string | null;
            enrichedAt: components["schemas"]["UtcTimestamp"];
            insight: components["schemas"]["news-insight.schema"];
        };
        /**
         * NewsArticle
         * @description A normalized news article. Enrichment is present only when AI enrichment succeeded.
         */
        "news-article.schema": {
            id: components["schemas"]["Uuid"];
            symbols: components["schemas"]["Symbol"][];
            headline: string;
            source: string;
            url: string;
            publishedAt: components["schemas"]["UtcTimestamp"];
            rawSummary: string | null;
            enrichment: components["schemas"]["enrichment.schema"] | null;
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem.schema"];
            };
        };
    };
    parameters: {
        /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
        CorrelationId: components["schemas"]["Uuid"];
        /** @description UUID identifying one order intent. Reuse it only when retrying the same request. */
        IdempotencyKey: components["schemas"]["Uuid"];
        OrderId: components["schemas"]["Uuid"];
        /** @description Maximum number of items to return. The server applies a configurable default and an upper bound (by default 100 and 500), and larger values are capped. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPortfolio: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["portfolio-summary.schema"];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    listPositions: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Positions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["position.schema"][];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                /** @description Only return orders in these statuses. */
                status?: components["schemas"]["OrderStatus"][];
                /** @description Maximum number of items to return. The server applies a configurable default and an upper bound (by default 100 and 500), and larger values are capped. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order.schema"][];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    placeOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
                /** @description UUID identifying one order intent. Reuse it only when retrying the same request. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["place-order-request.schema"];
            };
        };
        responses: {
            /** @description Order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order.schema"];
                };
            };
            /** @description Order awaiting confirmation or outcome verification */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order.schema"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order.schema"];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    confirmOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["order-confirmation-request.schema"];
            };
        };
        responses: {
            /** @description Resulting order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["order.schema"];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                orderId?: components["schemas"]["Uuid"];
                /** @description Maximum number of items to return. The server applies a configurable default and an upper bound (by default 100 and 500), and larger values are capped. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Executions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["execution.schema"][];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    getWatchlist: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watchlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["watchlist.schema"];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    addWatchlistItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["add-watchlist-item-request.schema"];
            };
        };
        responses: {
            /** @description Updated watchlist */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["watchlist.schema"];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    removeWatchlistItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                symbol: components["schemas"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    searchInstruments: {
        parameters: {
            query: {
                q: string;
                /** @description Maximum number of items to return. The server applies a configurable default and an upper bound (by default 100 and 500), and larger values are capped. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching instruments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["instrument.schema"][];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
    listNews: {
        parameters: {
            query: {
                symbol: components["schemas"]["Symbol"];
                /** @description Maximum number of items to return. The server applies a configurable default and an upper bound (by default 100 and 500), and larger values are capped. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description UUID chosen by the client per user action. The server generates one if it is absent or malformed. Used for tracing only. */
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description News articles. Successful empty refreshes return an empty array. Unavailable refreshes may return retained articles. */
            200: {
                headers: {
                    /** @description FRESH after a recent successful refresh, STALE while refresh is due, UNAVAILABLE when refresh cannot complete. */
                    "X-News-Status"?: "FRESH" | "STALE" | "UNAVAILABLE";
                    /** @description Last successful refresh time, including empty results. Omitted before the first success. */
                    "X-News-Last-Refreshed-At"?: components["schemas"]["UtcTimestamp"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["news-article.schema"][];
                };
            };
            "4XX": components["responses"]["Problem"];
            "5XX": components["responses"]["Problem"];
        };
    };
}
