security.protocol=SSL
ssl.keystore.type=PEM
ssl.keystore.location=/run/secrets/kafka_operator_keystore
ssl.truststore.type=PEM
ssl.truststore.location=/run/secrets/kafka_ca
ssl.endpoint.identification.algorithm=https
ssl.enabled.protocols=TLSv1.2,TLSv1.3
